### ISSUE TITLE
Lost connection to MagicMirror after going to 2.21.0 of MM

### ISSUE THREAD

**Issue by fribse** [sindrebroch/ha-magicmirror#18]
## Version of the custom_component

1.4.0

## Configuration

```yaml

Add your logs here.
Logger: homeassistant.config_entries
Source: config_entries.py:783
First occurred: 19.02.15 (1 occurrences)
Last logged: 19.02.15

Config entry '10.11.12.17' for magicmirror integration not ready yet; Retrying in background

Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 18.59.20 (4 occurrences)
Last logged: 18.59.27

Config entry '10.11.12.17' for magicmirror integration not ready yet; Retrying in background
```

## Describe the bug
After the upgrade of MagicMirror from 2.20 to 2.21 the integration doesn't work.
I think the update of HA to 2022.11.x also had an effect.

![billede](https://user-images.githubusercontent.com/13660621/204152182-926d04ed-7b47-4124-91d3-0444ee1474ff.png)

## Debug log

```text
2022-11-27 19:07:21.278 DEBUG (MainThread) [custom_components.magicmirror] GET url=http://10.11.12.17:8080/api/mmUpdateAvailable. headers={'accept': 'application/json', 'Authorization': 'Bearer b9911c8282f943faac207140f4e8ea0a'}
2022-11-27 19:07:35.399 DEBUG (MainThread) [custom_components.magicmirror] Finished fetching magicmirror data in 14.121 seconds (success: False)
```
