### ISSUE TITLE
If ScreenCast is installed on the MagicMirror, the integration doesn't work.

### ISSUE THREAD

**Issue by fribse** [sindrebroch/ha-magicmirror#2]
## Version of the custom_component

1.1.4
## Configuration

![billede](https://user-images.githubusercontent.com/13660621/153771104-6ac43759-9467-4c7f-ac0a-9366998c1e56.png)

```yaml
                {
                        module: "MMM-Remote-Control",
                        config: {
                                apiKey: 'b9911c8282f943faac207140f4e8ea0a',
                                showModuleApiMenu: true,
                                pm2ProcessName: 'MagicMirror',
//                              customCommand: {
//                                      playGhostvideo: '/home/pi/randomfile.sh'
//                                      }
                                },
                },/*
                {
                        module: "MMM-Screencast",
                        position: "'bottom_right", // This position is for a hidden <div /> and not the screencast window
                        config: {
                                position: "bottomRight",
                                castName: "Spejl",
                                height: 300,
                                width: 500,
                        }
                },*/

```

As soon as I uncomment the Screencast module, the integration goes away.

## Describe the bug
If I activate the Screencast module in MagicMirror, the integration doesn't work.
I can go to 'IP:8080/remote.html' with a browser and turn the monitor on/off etc.

## Debug log

```text

Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.magicmirror
Source: helpers/update_coordinator.py:219
Integration: Magic Mirror (documentation, issues)
First occurred: 18.39.45 (3 occurrences)
Last logged: 19.54.28

Error fetching magicmirror data: Cannot connect to host 10.11.12.17:8080 ssl:default [Connect call failed ('10.11.12.17', 8080)]

```
